version: "3.9"
services:
#mongodb database container
  database:
    container_name: mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=node-tuts
    ports:
      - 27017:27017
    restart: always
    volumes: 
      - database:/data/db

#node js backend container
  backend:
    container_name: node_app
    build: 
      context: .
      network: host
    ports:
      - 3000:3000
    environment:
      DB_URI: "mongodb://database:27017/node-tuts"
    depends_on:
      - database


volumes:
  database: {}